algoritmo "Exercício 03"
// Função : Efetuar a multiplicação de dois numeros digitados
// Autor : Bianca Martins Gonçalves
// Data : 21/03/2021
// Seção de Declarações 
var numero1, numero2, resultadodamultiplicacao : real


inicio
// Seção de Comandos 

escreval("insira numero1")
leia(numero1)
escreval("insira numero2")
leia(numero2)
escreval("resultadodamultiplicacao:",numero1*numero2)

fimalgoritmo
