algoritmo "Exercício 04"
// Função : Efetuar a soma de três números digitados
// Autor : Bianca Martins Gonçalves
// Data : 21/03/2021
// Seção de Declarações 
var numero1, numero2, numero3, resultadodasoma : real


inicio
// Seção de Comandos 

escreval("insira numero1")
leia(numero1)
escreval("insira numero2")
leia(numero2)
escreval("insira numero3")
leia(numero3)
escreval("resultadodasoma=", numero1 + numero2 + numero3)

fimalgoritmo
