algoritmo "Exercício04"
// Função : Apresentar os números de 1 até 100, com a opção de uma nova apresentação.
// Autor : Bianca Martins Gonçalves
// Data : 03/05/2021
// Seção de Declarações 
var
n: inteiro
resposta: caracter
inicio
// Seção de Comandos 
repita
para n de 1 ate 100 passo 1 faca
escreval (n)
fimpara
escreval ("Deseja continuar? Digite s para sim e n para nao")
leia (resposta)
ate resposta = "n"

fimalgoritmo
