algoritmo "Exercício06"
// Função :Conversão de graus Farenheit para Celsius sabendo-se que a fórmula para conversão é: C= 5/9 * (F –32)
// Autor : Bianca Martins Gonçalves
// Data : 08/05/2021
// Seção de Declarações 
var

celsius, farenheit: real

inicio
// Seção de Comandos 
escreval ("digite a temperatura de farenheit")
leia (farenheit)

celsius <- (5/9* (farenheit - 32))
escreval (celsius)

fimalgoritmo
