algoritmo "Exercício12"
// Função : Calcular a quantidade de dias vividos por uma pessoa, a partir da quantidade de anos que ela forneça.
// Autor : Bianca Martins Gonçalves
// Data : 09/05/2021
// Seção de Declarações 
var
dias, anos: real
inicio
// Seção de Comandos
escreval ("digite a quantidade de anos vividos")
leia (anos)

dias <- anos*365

escreval ("Considerando que os anos tenham 365 dias cada, a pessoa viveu:", dias," dias")
fimalgoritmo
