algoritmo "Exercício01"
// Função : Criar um programa que some dois números dos tipo real.
// Autor : Bianca Martins Gonçalves
// Data : 24/05/2021
// Seção de Declarações 
var

numero01, numero02, soma: real

inicio
// Seção de Comandos 
escreval("Insira o primeiro número")
leia(numero01)

escreval("Insira o segundo número")
leia(numero02)

soma<- numero01 + numero02

escreval("A soma é igual a: ", soma)

fimalgoritmo
