algoritmo "Exercício 01"
// Função : Elaborar um algoritmo em pseudocodigo que efetue a leitura de um número inteiro e apresentar uma mensagem informando se o número é par ou ímpar.
// Autor : Bianca Martins Gonçalves
// Data : 07/06/2021
// Seção de Declarações 
var
numero: inteiro
inicio
// Seção de Comandos
escreval ("Digite um número")
leia(numero)
se(numero mod 2 = 0) entao
escreval("O numero ",numero," é par")
senao
escreval("O numero ",numero," é ímpar")
fimse
fimalgoritmo
