algoritmo "Exercício14"
// Função :
// Autor :
// Data : 19/06/2021
// Seção de Declarações 
var
numero : inteiro
inicio
// Seção de Comandos 
escreval("Digite um numero")
leia(numero)
se (numero > 0) e (numero mod 2 = 0) entao
escreval("O numero é par e positivo")
senao
se(numero > 0) e (numero mod 2 <> 0) entao
escreval("O numero é impar e positivo")
senao
escreval("O numero não é positivo")
fimse
fimse
fimalgoritmo
