algoritmo "Exercício16"
// Função :
// Autor :
// Data : 19/06/2021
// Seção de Declarações 
var
salario, financiamento: real
inicio
// Seção de Comandos 
escreval("Digite o salário: ")
leia(salario)
escreval("Digite o financiamento pretendido: ")
leia(financiamento)
se (financiamento <= 5 * salario) entao
escreval("Financiamento concedido, obrigado por nos consultar")
senao
escreval("Financiamento negado, obrigado por nos consultar")
fimse
fimalgoritmo
