algoritmo "Exercício09"
// Função :
// Autor :
// Data : 22/06/2021
// Seção de Declarações 
var
NR,CONTADOR,FATORIAL : INTEIRO
inicio
// Seção de Comandos 
FATORIAL <- 1
ESCREVA ("ENTRE COM O NÚMERO :")
LEIA(NR)
PARA CONTADOR DE 1 ATE NR FACA
FATORIAL<- FATORIAL * CONTADOR
FIMPARA
SE (NR = 0) ENTAO
ESCREVA ("FATORIAL DE ", NR, " = ", 1)
SENAO
ESCREVA ("FATORIAL DE ", NR, " = ", FATORIAL)
FIMSE
fimalgoritmo
